- name: Install wasm-pack
  run: |
    curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
- name: Build livereload-client WASM
  run: |
    wasm-pack build --target web crates/livereload-client
