allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@arborium/arborium@2.18.0'
  - '@bearcove/vox-core@0.10.0-rc.0'
  - '@bearcove/vox-tcp@0.10.0-rc.0'
  - '@bearcove/vox-wire@0.10.0-rc.0'
  - '@bearcove/vox-ws@0.10.0-rc.0'
overrides:
  "monaco-editor": "npm:@codingame/monaco-vscode-editor-api@31.0.1"
  "@codingame/monaco-vscode-api": "31.0.1"
  "@codingame/monaco-vscode-base-service-override": "31.0.1"
  "@codingame/monaco-vscode-bulk-edit-service-override": "31.0.1"
  "@codingame/monaco-vscode-configuration-service-override": "31.0.1"
  "@codingame/monaco-vscode-editor-api": "31.0.1"
  "@codingame/monaco-vscode-editor-service-override": "31.0.1"
  "@codingame/monaco-vscode-environment-service-override": "31.0.1"
  "@codingame/monaco-vscode-extension-api": "31.0.1"
  "@codingame/monaco-vscode-extensions-service-override": "31.0.1"
  "@codingame/monaco-vscode-files-service-override": "31.0.1"
  "@codingame/monaco-vscode-host-service-override": "31.0.1"
  "@codingame/monaco-vscode-keybindings-service-override": "31.0.1"
  "@codingame/monaco-vscode-language-pack-cs": "31.0.1"
  "@codingame/monaco-vscode-language-pack-de": "31.0.1"
  "@codingame/monaco-vscode-language-pack-es": "31.0.1"
  "@codingame/monaco-vscode-language-pack-fr": "31.0.1"
  "@codingame/monaco-vscode-language-pack-it": "31.0.1"
  "@codingame/monaco-vscode-language-pack-ja": "31.0.1"
  "@codingame/monaco-vscode-language-pack-ko": "31.0.1"
  "@codingame/monaco-vscode-language-pack-pl": "31.0.1"
  "@codingame/monaco-vscode-language-pack-pt-br": "31.0.1"
  "@codingame/monaco-vscode-language-pack-qps-ploc": "31.0.1"
  "@codingame/monaco-vscode-language-pack-ru": "31.0.1"
  "@codingame/monaco-vscode-language-pack-tr": "31.0.1"
  "@codingame/monaco-vscode-language-pack-zh-hans": "31.0.1"
  "@codingame/monaco-vscode-language-pack-zh-hant": "31.0.1"
  "@codingame/monaco-vscode-languages-service-override": "31.0.1"
  "@codingame/monaco-vscode-layout-service-override": "31.0.1"
  "@codingame/monaco-vscode-localization-service-override": "31.0.1"
  "@codingame/monaco-vscode-log-service-override": "31.0.1"
  "@codingame/monaco-vscode-model-service-override": "31.0.1"
  "@codingame/monaco-vscode-monarch-service-override": "31.0.1"
  "@codingame/monaco-vscode-quickaccess-service-override": "31.0.1"
  "@codingame/monaco-vscode-textmate-service-override": "31.0.1"
  "@codingame/monaco-vscode-theme-defaults-default-extension": "31.0.1"
  "@codingame/monaco-vscode-theme-service-override": "31.0.1"
  "@codingame/monaco-vscode-view-banner-service-override": "31.0.1"
  "@codingame/monaco-vscode-view-common-service-override": "31.0.1"
  "@codingame/monaco-vscode-view-status-bar-service-override": "31.0.1"
  "@codingame/monaco-vscode-view-title-bar-service-override": "31.0.1"
  "@codingame/monaco-vscode-views-service-override": "31.0.1"
  "@codingame/monaco-vscode-workbench-service-override": "31.0.1"
  "vscode": "npm:@codingame/monaco-vscode-extension-api@31.0.1"
