use crate::harness::*;
use crate::*;
use std::time::Duration;

pub mod authoring_lsp;
pub mod basic;
pub mod boot_contract;
pub mod build_steps;
pub mod cache_busting;
pub mod code_execution;
pub mod content;
pub mod dead_links;
pub mod editor;
pub mod error_detection;
pub mod frontmatter_schemas;
pub mod internal_links;
pub mod livereload;
pub mod mermaid;
pub mod multi_source;
pub mod picante_cache;
pub mod renames;
pub mod rendered_markdown;
pub mod sass;
pub mod search;
pub mod section_pages;
pub mod shortcode_invalidation;
pub mod static_assets;
pub mod templates;
